title: awesome-learning
lang: en
description: Extends the continuous integration documentation capabilities of GitHub pages for everyone!

remote_theme: rundocs/jekyll-rtd-theme

readme_index:
  with_frontmatter: true

markdown: kramdown # For mathematical formula
kramdown:
  syntax_highlighter: rouge
  syntax_highlighter_opts: # Rouge Options › https://github.com/jneen/rouge#full-options
    css_class: highlight
    # default_lang: console
    span:
      line_numbers: false
    block:
      line_numbers: true
      start_line: 1

exclude:
  - Makefile
  - CNAME
  - Gemfile
  - Gemfile.lock
